services:
  node1:
    build: .
    container_name: raft-node1
    hostname: node1
    networks: [raft-cluster]
    ports: ["50051:50051"]
    environment:
      NODE_ID:   1
      NODE_PORT: 50051
      PEERS:     "2:node2:50052,3:node3:50053"

  node2:
    build: .
    container_name: raft-node2
    hostname: node2
    networks: [raft-cluster]
    ports: ["50052:50052"]
    environment:
      NODE_ID:   2
      NODE_PORT: 50052
      PEERS:     "1:node1:50051,3:node3:50053"

  node3:
    build: .
    container_name: raft-node3
    hostname: node3
    networks: [raft-cluster]
    ports: ["50053:50053"]
    environment:
      NODE_ID:   3
      NODE_PORT: 50053
      PEERS:     "1:node1:50051,2:node2:50052"

networks:
  raft-cluster:
    driver: bridge